### ISSUE TITLE
Provide installation steps

### ISSUE THREAD

**Issue by nfischer** [Jeff-Russ/bash-boolean-helpers#1]
This package looks like a neat library. It'd be great if you could provide installation steps toward the top, and perhaps with steps on how to include it in a bash script (does it use `source /path/to/bool_helpers.sh`, is it something I can source in my bashrc to get global use in my shell, etc.). I'm guessing the short answer to those questions is "_yea", but it'd be cool for someone else who's just starting out to be able to use this.

Also, it'd be great if you could get [CI](travis-ci.org) up and running for this, since I think that would promote adoption. You could also use that to test under zsh and other shells, much like [how nvm does it](https://travis-ci.org/creationix/nvm).

**Comment by Jeff-Russ** [comment]
I generally like to keep my .bashrc light and most of the time I'm making scripts, not actually in the shell. 
I've just been dropping in a function or two as needed per-script so I guess that's why it never occurred to 
me to put installation instructions. That said, after test driving it in the shell it actually really made 
being in the shell quicker and easier. Maybe I'll make an installer for it with shelljs! ha!

**Comment by Jeff-Russ** [comment]
Aight. Added:  
- install.sh
- uninstall.sh
- a man page

This house is clean.
